---
# yaml-language-server: $schema=https://raw.githubusercontent.com/j178/prek/refs/heads/master/prek.schema.json
minimum_prek_version: 0.2.29
default_install_hook_types:
  - pre-commit
default_stages:
  - pre-commit
# define priority: 0 for linters that don't modify sources
# leave fixers with priority: null so they run sequentially
repos:
  # "Built-in Fast Hooks" from prek.
  - repo: builtin
    hooks:
      - id: check-added-large-files
        name: Check for large files
        priority: 0

      - id: check-case-conflict
        name: Check for files that would conflict in case-insensitive filesystems
        priority: 0

      - id: trailing-whitespace
        name: Fix trailing whitespace
        types: [text]

      - id: end-of-file-fixer
        name: Fix newline at EOF

      - id: fix-byte-order-marker
        name: Fix UTF-8 byte order marker

      - id: check-json
        name: Check JSON files
        priority: 0
        types: [json]

      - id: check-toml
        name: Check TOML files
        priority: 0
        types: [toml]

      - id: check-yaml
        name: Check YAML files
        priority: 0
        types: [yaml]

      - id: mixed-line-ending
        name: Fix line endings
        types: [text]

      - id: check-merge-conflict
        name: Check for merge conflicts
        priority: 0

      - id: detect-private-key
        name: Check for private keys
        priority: 0

  - repo: local
    hooks:
      - id: actionlint
        name: Check Github Workflows
        priority: 0
        language: system
        entry: uv
        args: ["run", "--only-dev", "actionlint"]
        env:
          UV_FROZEN: "1"
        # run across all actions if any are touched
        require_serial: true
        pass_filenames: false
        files:
          glob:
            - .github/**/*.yml

      - id: jsonschema-github-workflows
        name: Check Github Workflows Schema
        priority: 0
        require_serial: true
        language: system
        entry: uv
        args: ["run", "--only-dev", "check-jsonschema", "--builtin-schema", "vendor.github-workflows"]
        env:
          UV_FROZEN: "1"
        types: [yaml]
        files:
          glob:
            - ".github/workflows/*.{yml,yaml}"

      - id: jsonschema-github-workflow-timeouts
        name: Check Github Workflows Timeouts
        priority: 0
        require_serial: true
        language: system
        entry: uv
        args: ["run", "--only-dev", "check-jsonschema", "--builtin-schema", "custom.github-workflows-require-timeout"]
        env:
          UV_FROZEN: "1"
        types: [yaml]
        files:
          glob:
            - ".github/workflows/*.{yml,yaml}"

      - id: zizmor
        name: Check Github Actions Security
        priority: 0
        language: system
        entry: uv
        args: ["run", "--only-dev", "zizmor", "--pedantic", "--offline", "."]
        env:
          UV_FROZEN: "1"
        # run across all actions if any are touched
        require_serial: true
        pass_filenames: false
        files:
          glob:
            - .github/**/*.yml

      - id: validate-pyproject
        name: Check pyproject.toml
        priority: 0
        language: system
        entry: uv
        args: ["run", "--only-dev", "validate-pyproject"]
        env:
          UV_FROZEN: "1"
        require_serial: true
        files:
          glob:
            - pyproject.toml

      - id: typos
        name: Check spelling
        priority: 0
        language: system
        entry: uv
        args: ["run", "--only-dev", "typos", "--force-exclude"]
        env:
          UV_FROZEN: "1"
        require_serial: true

      - id: rumdl
        name: Fix Markdown
        language: system
        entry: uv
        args: ["run", "--only-dev", "rumdl", "check", "--fix"]
        env:
          UV_FROZEN: "1"
        require_serial: true
        types: ["markdown"]

      - id: yamlfmt
        name: Format YAML
        language: system
        entry: uv
        args: ["run", "--only-dev", "yamlfmt"]
        env:
          UV_FROZEN: "1"
        require_serial: true
        types: ["yaml"]

      # slower rust checks
      # each one runs sequentially for now

      - id: cargo-check
        name: Check Rust compilation
        language: system
        entry: cargo
        args: ["check", "--workspace"]
        env:
          RUSTFLAGS: "-D warnings"
        # runs across all files if any are touched
        require_serial: true
        pass_filenames: false
        files:
          glob:
            - Cargo.toml
            - Cargo.lock
            - "**/*.rs"

      - id: cargo-clippy
        name: Check Rust lints
        language: system
        entry: cargo
        args: ["clippy", "--workspace", "--", "-D", "warnings"]
        # runs across all files if any are touched
        require_serial: true
        pass_filenames: false
        files:
          glob:
            - Cargo.toml
            - Cargo.lock
            - "**/*.rs"

      - id: cargo-test
        name: Check Rust tests
        language: system
        entry: cargo
        args: ["test", "--workspace"]
        # run across all files if any are touched
        require_serial: true
        pass_filenames: false
        files:
          glob:
            - Cargo.toml
            - Cargo.lock
            - "**/*.rs"

      - id: cargo-rustdoc
        name: Check Rust documentation
        language: system
        entry: cargo
        args: ["rustdoc"]
        env:
          RUSTDOCFLAGS: "-D warnings"
        # runs across all files if any are touched
        require_serial: true
        pass_filenames: false
        files:
          glob:
            - Cargo.toml
            - Cargo.lock
            - "**/*.rs"
            - "README.*"

      - id: cargo-fix
        name: Fix Rust problems
        language: system
        pass_filenames: false
        require_serial: true
        entry: cargo
        args: ["fix", "--workspace", "--allow-dirty", "--allow-staged"]
        types: ["rust"]

      - id: cargo-fmt
        name: Fix Rust formatting
        language: system
        entry: cargo
        args: ["fmt", "--all"]
        # runs across all files if any are touched
        require_serial: true
        pass_filenames: false
        types: [rust]

  # self-checks for this configuration file
  - repo: meta
    hooks:
      - id: check-hooks-apply
        name: Check prek hooks match at least one file
        priority: 0
        files:
          glob:
            - .pre-commit-config.yml

      - id: check-useless-excludes
        name: Check prek excludes match include pattern
        priority: 0
        files:
          glob:
            - .pre-commit-config.yml
