[licenses]
allow = [
    "Apache-2.0",
    "MIT",
    "MIT-0",
    "BSD-2-Clause",
    "Unicode-3.0",
]
confidence-threshold = 1.0

[bans]
multiple-versions = "deny"
wildcards = "deny"
skip = [
    "hashbrown:0.14.5",
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
