.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pegon 1  "pegon 0.1.0" 
.SH NAME
pegon \- A slightly fast Java linter and code formatter, written in Rust
.SH SYNOPSIS
\fBpegon\fR [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] <\fIsubcommands\fR>
.SH DESCRIPTION
A slightly fast Java linter and code formatter, written in Rust.
.PP
More sentence
.SH OPTIONS
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH SUBCOMMANDS
.TP
pegon\-check(1)
Run pegon on the given files or directories
.TP
pegon\-format(1)
Run the pegon formatter on the given files or directories
.TP
pegon\-server(1)
Run the language server
.SH VERSION
v0.1.0
.SH AUTHORS
Robert Muir <rmuir@apache.org>
