.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pegon-server 1  "server 0.1.0" 
.SH NAME
pegon\-server \- Run the language server
.SH SYNOPSIS
\fBpegon server\fR [\fB\-\-stdio\fR] [\fB\-\-socket\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fB\-V\fR|\fB\-\-version\fR] 
.SH DESCRIPTION
Run the language server
.SH OPTIONS
.TP
\fB\-\-stdio\fR
Use standard I/O streams (default)
.TP
\fB\-\-socket\fR \fI<PORT>\fR
Listen on loopback TCP socket
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help
.TP
\fB\-V\fR, \fB\-\-version\fR
Print version
.SH VERSION
v0.1.0
