.ie \n(.g .ds Aq \(aq
.el .ds Aq '
.TH pegon-check 1  "check " 
.SH NAME
pegon\-check \- Run pegon on the given files or directories
.SH SYNOPSIS
\fBpegon check\fR [\fB\-\-fix\fR] [\fB\-\-output\-format\fR] [\fB\-h\fR|\fB\-\-help\fR] [\fIFILES\fR] 
.SH DESCRIPTION
Run pegon on the given files or directories.
.PP
More information
.SH OPTIONS
.TP
\fB\-\-fix\fR
Apply fixes to resolve lint violations
.TP
\fB\-\-output\-format\fR \fI<FMT>\fR [default: full]
Diagnostic error format
.br

.br
\fIPossible values:\fR
.RS 14
.IP \(bu 2
full: Cargo\-style format
.IP \(bu 2
concise: Grep\-style format
.RE
.RS
May also be specified with the \fBPEGON_OUTPUT_FORMAT\fR environment variable. 
.RE
.TP
\fB\-h\fR, \fB\-\-help\fR
Print help (see a summary with \*(Aq\-h\*(Aq)
.TP
[\fIFILES\fR]
List of files or directories to check

Use `\-` for standard input. [default: CWD]
