---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: CI

permissions: {}

# nothing tree-sitter-related plays well with dependabot :)
env:
  TS_QUERY_LS_VERSION: "v3.15.1"
  TREE_SITTER_VERSION: "v0.26.9"
  TREE_SITTER_JAVA_ORCHARD_VERSION: "v0.5.10"

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - "*"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    name: CI checks
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        include:
          - runner: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
          - runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
          - runner: macos-26-intel
            target: x86_64-apple-darwin
          - runner: macos-26
            target: aarch64-apple-darwin
          - runner: windows-2022
            target: x86_64-pc-windows-msvc
    timeout-minutes: 15
    steps:
      - name: Checkout repository
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      # Has no package so we cache the binary
      - name: Cache ts_query_ls binary
        id: cache-ts-query-ls
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.local/bin/ts_query_ls
            ~/.local/bin/ts_query_ls.exe
          key: ts_query_ls-${{ env.TS_QUERY_LS_VERSION }}-${{ runner.os }}-${{ runner.arch }}

      - name: Setup ts_query_ls (unix)
        if: ${{ steps.cache-ts-query-ls.outputs.cache-hit != 'true' && matrix.target != 'x86_64-pc-windows-msvc' }}
        run: |
          mkdir -p ~/.local/bin
          curl --fail --location "${TS_QUERY_LS_DIST}" | tar -zxC ~/.local/bin ts_query_ls
        shell: bash
        working-directory: ${{ runner.temp }}
        env:
          TS_QUERY_LS_DIST: "https://github.com/ribru17/ts_query_ls/releases/download/${{ env.TS_QUERY_LS_VERSION }}/ts_query_ls-${{ matrix.target }}.tar.gz"

      - name: Setup ts_query_ls (windows)
        if: ${{ steps.cache-ts-query-ls.outputs.cache-hit != 'true' && matrix.target == 'x86_64-pc-windows-msvc' }}
        run: |
          mkdir -p ~/.local/bin
          curl --fail --location -o ts_query_ls.zip "${TS_QUERY_LS_DIST}"
          unzip ts_query_ls.zip
          cp ts_query_ls.exe ~/.local/bin
        shell: bash
        working-directory: ${{ runner.temp }}
        env:
          TS_QUERY_LS_DIST: "https://github.com/ribru17/ts_query_ls/releases/download/${{ env.TS_QUERY_LS_VERSION }}/ts_query_ls-${{ matrix.target }}.zip"

      - name: Add ts_query_ls to PATH
        run: |
          TARGET_DIR="${HOME:-$USERPROFILE}"
          echo "${TARGET_DIR}/.local/bin" >> "${GITHUB_PATH}"
        shell: bash

      # Has no wasm, so we must build it. Cache the built library.
      - name: Cache tree-sitter-java-orchard library
        id: cache-tree-sitter-java-orchard
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        with:
          path: |
            ~/.local/lib/java-orchard.so
            ~/.local/lib/java-orchard.dll
            ~/.local/lib/java-orchard.dylib
          key: java-orchard-${{ env.TREE_SITTER_JAVA_ORCHARD_VERSION }}-${{ runner.os }}-${{ runner.arch }}

      - name: Clone parser
        if: ${{ steps.cache-tree-sitter-java-orchard.outputs.cache-hit != 'true' }}
        run: |
          git clone --branch "${BRANCH}" --depth 1 https://codeberg.org/grammar-orchard/tree-sitter-java-orchard.git
        shell: bash
        env:
          BRANCH: ${{ env.TREE_SITTER_JAVA_ORCHARD_VERSION }}
        working-directory: ${{ runner.temp }}

      # Mutates tags, so just track master.
      - name: Set up tree-sitter
        if: ${{ steps.cache-tree-sitter-java-orchard.outputs.cache-hit != 'true' }}
        uses: tree-sitter/setup-action/cli@1868a545ffb91bdc221d14a168b5b6d8de4a28b3 # master
        with:
          tree-sitter-ref: ${{ env.TREE_SITTER_VERSION }}

      - name: Generate parser
        if: ${{ steps.cache-tree-sitter-java-orchard.outputs.cache-hit != 'true' }}
        run: tree-sitter generate
        shell: bash
        working-directory: ${{ runner.temp }}/tree-sitter-java-orchard

      - name: Build parser
        if: ${{ steps.cache-tree-sitter-java-orchard.outputs.cache-hit != 'true' }}
        run: tree-sitter build
        shell: bash
        working-directory: ${{ runner.temp }}/tree-sitter-java-orchard

      - name: Install parser
        if: ${{ steps.cache-tree-sitter-java-orchard.outputs.cache-hit != 'true' }}
        run: |
          mkdir -p ~/.local/lib
          cp java-orchard.so ~/.local/lib || cp java-orchard.dylib ~/.local/lib || cp java-orchard.dll ~/.local/lib
        shell: bash
        working-directory: ${{ runner.temp }}/tree-sitter-java-orchard

      - name: Setup uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          enable-cache: true
          prune-cache: false
          save-cache: ${{ github.event_name != 'pull_request' }}
          cache-dependency-glob: uv.lock
          cache-suffix: check

      - name: Setup node
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: npm

      - name: Setup rust cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1

      - name: Run checks
        run: make lint
        shell: bash
        env:
          CARGO_INCREMENTAL: 0
          CARGO_NET_RETRY: 10
